spring.application.name=processing-service

spring.kafka.bootstrap-servers=localhost:29092

spring.kafka.streams.application-id=processing-service
spring.kafka.streams.properties.commit.interval.ms=5000
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde



logging.level.root=INFO
server.port=8002