services:
  db:
    image: postgres:latest
    restart: always
    container_name: rta-e-commerce-db
    hostname: postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: ${RTA_DB_NAME}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/data:/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    networks:
      - internal
  zookeeper:
    image: zookeeper:latest
    container_name: rta-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - internal

  kafka:
    image: confluentinc/cp-kafka:7.9.0-1-ubi8
    user: "0:0"
    container_name: rta-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    depends_on:
      [ zookeeper ]
    healthcheck: { test: nc -z localhost 9092, interval: 1s, start_period: 120s }
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - internal
  debezium:
    image: debezium/connect:2.6
    container_name: rta-kafka-connect
    hostname: debezium
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
    healthcheck: { test: curl -f localhost:8083, interval: 1s, start_period: 120s }
    depends_on:
      - kafka
      - db
    networks:
      - internal

  debezium_deploy:
    image: debezium/connect:2.6
    depends_on:
      debezium: { condition: service_healthy }
    environment:
      KAFKA_ADDR: kafka:9092
      RTA_DB_HOST: ${RTA_DB_HOST}
      RTA_DB_PORT: ${RTA_DB_PORT}
      RTA_DB_NAME: ${RTA_DB_NAME}
      RTA_DB_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      RTA_DB_USER: ${SPRING_DATASOURCE_USERNAME}
    volumes:
      - ./debezium/register_postgres.sh:/register_postgres.sh
    entrypoint: ["bash", "/register_postgres.sh"]
    networks:
      - internal
  pinot:
    image: apachepinot/pinot:latest
    container_name: rta-pinot
    command: "QuickStart -type stream"
    ports:
      - "9000:9000"   # Web UI
      - "8099:8099"   # Broker port (optional)
      - "8000:8000"   # Add this line
    environment:
      JAVA_OPTS: >
        -Xms512m -Xmx1g
        -Dpinot.broker.host=rta-pinot
        -Dpinot.broker.client.queryPort=8000
    depends_on:
      - kafka
      - zookeeper
    networks:
      - internal

  pinot-add-orders-table:
    image: apachepinot/pinot:latest
    container_name: pinot-add-orders-table
    volumes:
      - ./pinot/config:/config
    command: >
      AddTable
      -schemaFile /config/orders/order_placed_schema.json
      -tableConfigFile /config/orders/order_placed_rt_table.json
      -controllerHost rta-pinot
      -exec
    restart: "no"
    depends_on:
      - pinot
    networks:
      - internal


  ingestion-service:
    build:
      context: ./ingestion-service
    container_name: rta-ingestion-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_PRODUCER_ACKS=${SPRING_KAFKA_PRODUCER_ACKS}
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_LINGER_MS=5
      - SPRING_KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS=30000
      - SPRING_KAFKA_PRODUCER_REQUEST_TIMEOUT_MS=20000
      - SERVER_PORT=${INGESTION_SERVER_PORT}

    depends_on:
      - kafka
    networks:
      - internal

  processing-service:
    build:
      context: ./processing-service
    container_name: rta-processing-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_PROCESSING_GROUP_ID}
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      - SPRING_KAFKA_PRODUCER_ACKS=${SPRING_KAFKA_PRODUCER_ACKS}
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_LINGER_MS=5
      - SPRING_KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS=30000
      - SPRING_KAFKA_PRODUCER_REQUEST_TIMEOUT_MS=20000
      - SERVER_PORT=${PROCESSING_SERVER_PORT}
    depends_on:
      - kafka
      - pinot
    networks:
      - internal

  analytics-service:
    build:
      context: ./analytics-service
    container_name: rta-analytics-service
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=${ANALYTICS_SERVER_PORT}
      - PINOT_TABLE=${ANALYTICS_PINOT_ORDER_PLACED_RT_TABLE}
      - PINOT_HOSTS=${ANALYTICS_PINOT_BROKER_HOSTS}
    depends_on:
      - kafka
    networks:
      - internal

volumes:
  kafka_data:
  postgres_data:

networks:
  internal:
