services:
  zookeeper:
    image: zookeeper:latest
    container_name: rta-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    networks:
      - internal
  kafka:
    image: confluentinc/cp-kafka:7.9.0-1-ubi8
    user: "0:0"
    container_name: rta-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
    depends_on:
      [ zookeeper ]
    healthcheck: { test: nc -z localhost 9092, interval: 1s, start_period: 120s }
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - internal

  ingestion-service:
    build:
      context: ./ingestion-service
    container_name: rta-ingestion-service
    ports:
      - "8001:8001"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_PRODUCER_ACKS=${SPRING_KAFKA_PRODUCER_ACKS}
      - SPRING_KAFKA_PRODUCER_RETRIES=3
      - SPRING_KAFKA_PRODUCER_LINGER_MS=5
      - SPRING_KAFKA_PRODUCER_DELIVERY_TIMEOUT_MS=30000
      - SPRING_KAFKA_PRODUCER_REQUEST_TIMEOUT_MS=20000
    depends_on:
      - kafka
    networks:
      - internal

  processing-service:
    build:
      context: ./processing-service
    container_name: rta-processing-service
    ports:
      - "8002:8002"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_PROCESSING_GROUP_ID}
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      - SERVER_PORT=${PROCESSING_SERVER_PORT}
    depends_on:
      - kafka
    networks:
      - internal

  analytics-service:
    build:
      context: ./analytics-service
    container_name: rta-analytics-service
    ports:
      - "8003:8003"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_KAFKA_CONSUMER_GROUP_ID=${SPRING_KAFKA_CONSUMER_ANALYTICS_GROUP_ID}
      - SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET=${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET}
      - SERVER_PORT=${ANALYTICS_SERVER_PORT}
    depends_on:
      - kafka
    networks:
      - internal

volumes:
  kafka_data:

networks:
  internal:
