### order-placed event request
POST {{baseUrl}}/order-placed
Content-Type: application/json

{
  "orderId": "1238",
  "customerId": "448",
  "totalAmount": 50.00,
  "createdAt": "{{$isoTimestamp}}",
  "products": [
    {
      "productId": "PROD-452",
      "quantity": 1,
      "price": 50.00
    }
  ]
}
###
